/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppConsultationsRouteImport } from './routes/app.consultations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDoctorScheduleRouteImport } from './routes/app.doctor-schedule'
import { Route as AppDoctorsRouteImport } from './routes/app.doctors'
import { Route as AppGroomingRouteImport } from './routes/app.grooming'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppLabRouteImport } from './routes/app.lab'
import { Route as AppMasterDataRouteImport } from './routes/app.master-data'
import { Route as AppNowServingRouteImport } from './routes/app.now-serving'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPharmacyRouteImport } from './routes/app.pharmacy'
import { Route as AppPrescriptionsRouteImport } from './routes/app.prescriptions'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppRefundsRouteImport } from './routes/app.refunds'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppVaccinationsRouteImport } from './routes/app.vaccinations'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalBookAppointmentRouteImport } from './routes/portal.book-appointment'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalMyAppointmentsRouteImport } from './routes/portal.my-appointments'
import { Route as PortalMyPetsRouteImport } from './routes/portal.my-pets'
import { Route as PortalPrescriptionsRouteImport } from './routes/portal.prescriptions'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as AppOwnersIndexRouteImport } from './routes/app.owners.index'
import { Route as AppOwnersIdRouteImport } from './routes/app.owners.$id'
import { Route as AppOwnersNewRouteImport } from './routes/app.owners.new'
import { Route as AppPetsIndexRouteImport } from './routes/app.pets.index'
import { Route as AppPetsIdRouteImport } from './routes/app.pets.$id'
import { Route as AppPetsNewRouteImport } from './routes/app.pets.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsRoute = AppConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorScheduleRoute = AppDoctorScheduleRouteImport.update({
  id: '/doctor-schedule',
  path: '/doctor-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppGroomingRoute = AppGroomingRouteImport.update({
  id: '/grooming',
  path: '/grooming',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataRoute = AppMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AppRoute,
} as any)
const AppNowServingRoute = AppNowServingRouteImport.update({
  id: '/now-serving',
  path: '/now-serving',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppRefundsRoute = AppRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppVaccinationsRoute = AppVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookAppointmentRoute = PortalBookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMyAppointmentsRoute = PortalMyAppointmentsRouteImport.update({
  id: '/my-appointments',
  path: '/my-appointments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMyPetsRoute = PortalMyPetsRouteImport.update({
  id: '/my-pets',
  path: '/my-pets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPrescriptionsRoute = PortalPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const AppOwnersIndexRoute = AppOwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnersIdRoute = AppOwnersIdRouteImport.update({
  id: '/owners/$id',
  path: '/owners/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnersNewRoute = AppOwnersNewRouteImport.update({
  id: '/owners/new',
  path: '/owners/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsIndexRoute = AppPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsIdRoute = AppPetsIdRouteImport.update({
  id: '/pets/$id',
  path: '/pets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsNewRoute = AppPetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book-appointment': typeof BookAppointmentRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/doctor-schedule': typeof AppDoctorScheduleRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/grooming': typeof AppGroomingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/lab': typeof AppLabRoute
  '/app/master-data': typeof AppMasterDataRoute
  '/app/now-serving': typeof AppNowServingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pharmacy': typeof AppPharmacyRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/queue': typeof AppQueueRoute
  '/app/refunds': typeof AppRefundsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/vaccinations': typeof AppVaccinationsRoute
  '/portal/book-appointment': typeof PortalBookAppointmentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/my-appointments': typeof PortalMyAppointmentsRoute
  '/portal/my-pets': typeof PortalMyPetsRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/owners/$id': typeof AppOwnersIdRoute
  '/app/owners/new': typeof AppOwnersNewRoute
  '/app/pets/$id': typeof AppPetsIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/app/owners/': typeof AppOwnersIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/doctor-schedule': typeof AppDoctorScheduleRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/grooming': typeof AppGroomingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/lab': typeof AppLabRoute
  '/app/master-data': typeof AppMasterDataRoute
  '/app/now-serving': typeof AppNowServingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pharmacy': typeof AppPharmacyRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/queue': typeof AppQueueRoute
  '/app/refunds': typeof AppRefundsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/vaccinations': typeof AppVaccinationsRoute
  '/portal/book-appointment': typeof PortalBookAppointmentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/my-appointments': typeof PortalMyAppointmentsRoute
  '/portal/my-pets': typeof PortalMyPetsRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/owners/$id': typeof AppOwnersIdRoute
  '/app/owners/new': typeof AppOwnersNewRoute
  '/app/pets/$id': typeof AppPetsIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/app/owners': typeof AppOwnersIndexRoute
  '/app/pets': typeof AppPetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book-appointment': typeof BookAppointmentRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/doctor-schedule': typeof AppDoctorScheduleRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/grooming': typeof AppGroomingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/lab': typeof AppLabRoute
  '/app/master-data': typeof AppMasterDataRoute
  '/app/now-serving': typeof AppNowServingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pharmacy': typeof AppPharmacyRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/queue': typeof AppQueueRoute
  '/app/refunds': typeof AppRefundsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/vaccinations': typeof AppVaccinationsRoute
  '/portal/book-appointment': typeof PortalBookAppointmentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/my-appointments': typeof PortalMyAppointmentsRoute
  '/portal/my-pets': typeof PortalMyPetsRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/owners/$id': typeof AppOwnersIdRoute
  '/app/owners/new': typeof AppOwnersNewRoute
  '/app/pets/$id': typeof AppPetsIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/app/owners/': typeof AppOwnersIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/book-appointment'
    | '/login'
    | '/playground'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/billing'
    | '/app/branches'
    | '/app/calendar'
    | '/app/consultations'
    | '/app/dashboard'
    | '/app/doctor-schedule'
    | '/app/doctors'
    | '/app/grooming'
    | '/app/inventory'
    | '/app/lab'
    | '/app/master-data'
    | '/app/now-serving'
    | '/app/onboarding'
    | '/app/payments'
    | '/app/pharmacy'
    | '/app/prescriptions'
    | '/app/queue'
    | '/app/refunds'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/suppliers'
    | '/app/tenants'
    | '/app/vaccinations'
    | '/portal/book-appointment'
    | '/portal/dashboard'
    | '/portal/invoices'
    | '/portal/my-appointments'
    | '/portal/my-pets'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/app/'
    | '/portal/'
    | '/app/owners/$id'
    | '/app/owners/new'
    | '/app/pets/$id'
    | '/app/pets/new'
    | '/app/owners/'
    | '/app/pets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-appointment'
    | '/login'
    | '/playground'
    | '/pricing'
    | '/signup'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/billing'
    | '/app/branches'
    | '/app/calendar'
    | '/app/consultations'
    | '/app/dashboard'
    | '/app/doctor-schedule'
    | '/app/doctors'
    | '/app/grooming'
    | '/app/inventory'
    | '/app/lab'
    | '/app/master-data'
    | '/app/now-serving'
    | '/app/onboarding'
    | '/app/payments'
    | '/app/pharmacy'
    | '/app/prescriptions'
    | '/app/queue'
    | '/app/refunds'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/suppliers'
    | '/app/tenants'
    | '/app/vaccinations'
    | '/portal/book-appointment'
    | '/portal/dashboard'
    | '/portal/invoices'
    | '/portal/my-appointments'
    | '/portal/my-pets'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/app'
    | '/portal'
    | '/app/owners/$id'
    | '/app/owners/new'
    | '/app/pets/$id'
    | '/app/pets/new'
    | '/app/owners'
    | '/app/pets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/book-appointment'
    | '/login'
    | '/playground'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/billing'
    | '/app/branches'
    | '/app/calendar'
    | '/app/consultations'
    | '/app/dashboard'
    | '/app/doctor-schedule'
    | '/app/doctors'
    | '/app/grooming'
    | '/app/inventory'
    | '/app/lab'
    | '/app/master-data'
    | '/app/now-serving'
    | '/app/onboarding'
    | '/app/payments'
    | '/app/pharmacy'
    | '/app/prescriptions'
    | '/app/queue'
    | '/app/refunds'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/suppliers'
    | '/app/tenants'
    | '/app/vaccinations'
    | '/portal/book-appointment'
    | '/portal/dashboard'
    | '/portal/invoices'
    | '/portal/my-appointments'
    | '/portal/my-pets'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/app/'
    | '/portal/'
    | '/app/owners/$id'
    | '/app/owners/new'
    | '/app/pets/$id'
    | '/app/pets/new'
    | '/app/owners/'
    | '/app/pets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookAppointmentRoute: typeof BookAppointmentRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultations': {
      id: '/app/consultations'
      path: '/consultations'
      fullPath: '/app/consultations'
      preLoaderRoute: typeof AppConsultationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doctor-schedule': {
      id: '/app/doctor-schedule'
      path: '/doctor-schedule'
      fullPath: '/app/doctor-schedule'
      preLoaderRoute: typeof AppDoctorScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doctors': {
      id: '/app/doctors'
      path: '/doctors'
      fullPath: '/app/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grooming': {
      id: '/app/grooming'
      path: '/grooming'
      fullPath: '/app/grooming'
      preLoaderRoute: typeof AppGroomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab': {
      id: '/app/lab'
      path: '/lab'
      fullPath: '/app/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master-data': {
      id: '/app/master-data'
      path: '/master-data'
      fullPath: '/app/master-data'
      preLoaderRoute: typeof AppMasterDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/now-serving': {
      id: '/app/now-serving'
      path: '/now-serving'
      fullPath: '/app/now-serving'
      preLoaderRoute: typeof AppNowServingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy': {
      id: '/app/pharmacy'
      path: '/pharmacy'
      fullPath: '/app/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions': {
      id: '/app/prescriptions'
      path: '/prescriptions'
      fullPath: '/app/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/refunds': {
      id: '/app/refunds'
      path: '/refunds'
      fullPath: '/app/refunds'
      preLoaderRoute: typeof AppRefundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vaccinations': {
      id: '/app/vaccinations'
      path: '/vaccinations'
      fullPath: '/app/vaccinations'
      preLoaderRoute: typeof AppVaccinationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/book-appointment': {
      id: '/portal/book-appointment'
      path: '/book-appointment'
      fullPath: '/portal/book-appointment'
      preLoaderRoute: typeof PortalBookAppointmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/my-appointments': {
      id: '/portal/my-appointments'
      path: '/my-appointments'
      fullPath: '/portal/my-appointments'
      preLoaderRoute: typeof PortalMyAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/my-pets': {
      id: '/portal/my-pets'
      path: '/my-pets'
      fullPath: '/portal/my-pets'
      preLoaderRoute: typeof PortalMyPetsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/prescriptions': {
      id: '/portal/prescriptions'
      path: '/prescriptions'
      fullPath: '/portal/prescriptions'
      preLoaderRoute: typeof PortalPrescriptionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/owners/': {
      id: '/app/owners/'
      path: '/owners'
      fullPath: '/app/owners/'
      preLoaderRoute: typeof AppOwnersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owners/$id': {
      id: '/app/owners/$id'
      path: '/owners/$id'
      fullPath: '/app/owners/$id'
      preLoaderRoute: typeof AppOwnersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owners/new': {
      id: '/app/owners/new'
      path: '/owners/new'
      fullPath: '/app/owners/new'
      preLoaderRoute: typeof AppOwnersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pets/': {
      id: '/app/pets/'
      path: '/pets'
      fullPath: '/app/pets/'
      preLoaderRoute: typeof AppPetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pets/$id': {
      id: '/app/pets/$id'
      path: '/pets/$id'
      fullPath: '/app/pets/$id'
      preLoaderRoute: typeof AppPetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pets/new': {
      id: '/app/pets/new'
      path: '/pets/new'
      fullPath: '/app/pets/new'
      preLoaderRoute: typeof AppPetsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppConsultationsRoute: typeof AppConsultationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDoctorScheduleRoute: typeof AppDoctorScheduleRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppGroomingRoute: typeof AppGroomingRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLabRoute: typeof AppLabRoute
  AppMasterDataRoute: typeof AppMasterDataRoute
  AppNowServingRoute: typeof AppNowServingRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRefundsRoute: typeof AppRefundsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppVaccinationsRoute: typeof AppVaccinationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOwnersIdRoute: typeof AppOwnersIdRoute
  AppOwnersNewRoute: typeof AppOwnersNewRoute
  AppPetsIdRoute: typeof AppPetsIdRoute
  AppPetsNewRoute: typeof AppPetsNewRoute
  AppOwnersIndexRoute: typeof AppOwnersIndexRoute
  AppPetsIndexRoute: typeof AppPetsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppConsultationsRoute: AppConsultationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDoctorScheduleRoute: AppDoctorScheduleRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppGroomingRoute: AppGroomingRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLabRoute: AppLabRoute,
  AppMasterDataRoute: AppMasterDataRoute,
  AppNowServingRoute: AppNowServingRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppQueueRoute: AppQueueRoute,
  AppRefundsRoute: AppRefundsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppVaccinationsRoute: AppVaccinationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppOwnersIdRoute: AppOwnersIdRoute,
  AppOwnersNewRoute: AppOwnersNewRoute,
  AppPetsIdRoute: AppPetsIdRoute,
  AppPetsNewRoute: AppPetsNewRoute,
  AppOwnersIndexRoute: AppOwnersIndexRoute,
  AppPetsIndexRoute: AppPetsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalBookAppointmentRoute: typeof PortalBookAppointmentRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalMyAppointmentsRoute: typeof PortalMyAppointmentsRoute
  PortalMyPetsRoute: typeof PortalMyPetsRoute
  PortalPrescriptionsRoute: typeof PortalPrescriptionsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookAppointmentRoute: PortalBookAppointmentRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalMyAppointmentsRoute: PortalMyAppointmentsRoute,
  PortalMyPetsRoute: PortalMyPetsRoute,
  PortalPrescriptionsRoute: PortalPrescriptionsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookAppointmentRoute: BookAppointmentRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
